ARG JUPYTERHUB_VERSION
FROM quay.io/jupyterhub/jupyterhub:$JUPYTERHUB_VERSION

# Install necessary Python packages
# hadolint ignore=DL3013
RUN python3 -m pip install --no-cache-dir \
    dockerspawner==13.0.0 \
    jupyterhub-nativeauthenticator \
    PyYAML \
    jupyter-client \
    jupyterlab==4.0.11 \
    notebook==7.0.7 \
    jupyter-collaboration


# RUN sudo apt-get install nodejs \
#     npm

# Create collaboration configuration file
# RUN mkdir -p /srv/jupyterhub \
#     && echo "projects:" > /srv/jupyterhub/collaboration_config.yml \
#     && echo "  vox:" >> /srv/jupyterhub/collaboration_config.yml \
#     && echo "    members:" >> /srv/jupyterhub/collaboration_config.yml \
#     && echo "      - user1" >> /srv/jupyterhub/collaboration_config.yml \
#     && echo "      - user2" >> /srv/jupyterhub/collaboration_config.yml \
#     && echo "      - user3" >> /srv/jupyterhub/collaboration_config.yml \
#     && echo "  mighty:" >> /srv/jupyterhub/collaboration_config.yml \
#     && echo "    members:" >> /srv/jupyterhub/collaboration_config.yml \
#     && echo "      - user4" >> /srv/jupyterhub/collaboration_config.yml \
#     && echo "      - user5" >> /srv/jupyterhub/collaboration_config.yml \
#     && echo "      - user6" >> /srv/jupyterhub/collaboration_config.yml

# Copy collaboration configuration file into the Docker image
# COPY /home/syedanwar/Desktop/Jmm/jupyterhub/jupyterhub-deploy-docker/basic-example/collaboration_config.yml /srv/jupyterhub/collaboration_config.yml
# COPY ./authenti.py /srv/jupyterhub/authenti.py

CMD ["jupyterhub", "-f", "/srv/jupyterhub/jupyterhub_config.py"]
